# -*- coding: utf-8 -*-
"""Lab1_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aj1Sg4_R2crd0eRNl9yjobvX1d11Xz1j
"""

!pip install fastapi uvicorn transformers torch pyngrok -q

code = '''
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from transformers import pipeline

app = FastAPI(title="Sentiment Analysis API", version="1.0")

sentiment_model = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-roberta-base-sentiment-latest"
)

class TextInput(BaseModel):
    text: str

@app.get("/")
def root():
    return {
        "name": "Sentiment Analysis API",
        "description": "Phan tich cam xuc van ban (Positive/Negative/Neutral)",
        "model": "cardiffnlp/twitter-roberta-base-sentiment-latest",
        "endpoints": ["/", "/health", "/predict"]
    }

@app.get("/health")
def health():
    return {"status": "ok", "model_loaded": True}

@app.post("/predict")
def predict(data: TextInput):
    if not data.text.strip():
        raise HTTPException(status_code=400, detail="Text khong duoc de trong")
    try:
        result = sentiment_model(data.text)[0]
        return {
            "text": data.text,
            "label": result["label"],
            "score": round(result["score"], 4)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
'''

with open("main.py", "w") as f:
    f.write(code)

print("Da tao file main.py!")

from pyngrok import ngrok
import subprocess, threading, time

# Dán token ngrok của bạn vào đây
ngrok.set_auth_token("YOUR_NGROK_TOKEN_HERE")  # Thay bằng token ngrok của bạn

# Tạo đường hầm ra ngoài internet
public_url = ngrok.connect(8000)
print("=== PUBLIC URL CUA BAN ===")
print(public_url)
print("==========================")

# Chạy server FastAPI
def run_server():
    subprocess.run(["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"])

thread = threading.Thread(target=run_server, daemon=True)
thread.start()
time.sleep(5)
print("Server da san sang!")

import requests

# Thay bằng URL của bạn từ bước trên
BASE_URL = "https://nonclinging-gabriel-bewhiskered.ngrok-free.dev"  # <-- đổi cái này

# Test GET /
r = requests.get(f"{BASE_URL}/")
print("GET /:", r.json())

# Test GET /health
r = requests.get(f"{BASE_URL}/health")
print("GET /health:", r.json())

# Test POST /predict
r = requests.post(f"{BASE_URL}/predict", json={"text": "I love this product!"})
print("POST /predict:", r.json())

r = requests.post(f"{BASE_URL}/predict", json={"text": "This is terrible."})
print("POST /predict:", r.json())

test_code = '''
import requests

BASE_URL = "https://nonclinging-gabriel-bewhiskered.ngrok-free.dev"  # đổi thành URL của bạn

def test_root():
    r = requests.get(f"{BASE_URL}/")
    assert r.status_code == 200
    print("GET /  OK:", r.json())

def test_health():
    r = requests.get(f"{BASE_URL}/health")
    assert r.status_code == 200
    print("GET /health  OK:", r.json())

def test_predict_positive():
    r = requests.post(f"{BASE_URL}/predict", json={"text": "I love this so much!"})
    assert r.status_code == 200
    print("Positive test  OK:", r.json())

def test_predict_negative():
    r = requests.post(f"{BASE_URL}/predict", json={"text": "This is absolutely terrible."})
    assert r.status_code == 200
    print("Negative test  OK:", r.json())

def test_empty_input():
    r = requests.post(f"{BASE_URL}/predict", json={"text": ""})
    assert r.status_code == 400
    print("Empty input  OK:", r.json())

if __name__ == "__main__":
    test_root()
    test_health()
    test_predict_positive()
    test_predict_negative()
    test_empty_input()
    print("\\nTat ca test deu pass!")
'''

with open("test_api.py", "w") as f:
    f.write(test_code)

print("Da tao test_api.py!")
req = """fastapi
uvicorn
transformers
torch
pyngrok
requests
"""

with open("requirements.txt", "w") as f:
    f.write(req)

print("Da tao requirements.txt!")
readme = """# Sentiment Analysis API

## Thong tin sinh vien
- Ho ten: KhanhTran1307
- MSSV: (dien MSSV cua ban)

## Mo hinh su dung
- Ten mo hinh: cardiffnlp/twitter-roberta-base-sentiment-latest
- Link: https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest
- Chuc nang: Phan tich cam xuc van ban, phan loai Positive / Negative / Neutral

## Chuc nang he thong
API nhan dau vao la mot doan van ban va tra ve nhan cam xuc cung voi do tin cay.

## Cai dat thu vien
pip install -r requirements.txt

## Chay chuong trinh
uvicorn main:app --host 0.0.0.0 --port 8000

## Huong dan goi API

### GET /
curl https://nonclinging-gabriel-bewhiskered.ngrok-free.dev/

### GET /health
curl https://nonclinging-gabriel-bewhiskered.ngrok-free.dev/health

### POST /predict
curl -X POST https://nonclinging-gabriel-bewhiskered.ngrok-free.dev/predict -H "Content-Type: application/json" -d '{"text": "I love this!"}'

Ket qua tra ve:
{
  "text": "I love this!",
  "label": "positive",
  "score": 0.9823
}

## Video demo
(them link video vao day sau khi quay)
"""

with open("README.md", "w") as f:
    f.write(readme)

print("Da tao README.md!")

import os
files = ["main.py", "test_api.py", "requirements.txt", "README.md"]
for f in files:
    print(f, "✓" if os.path.exists(f) else "✗ CHUA CO")

# GITHUB_USERNAME = "KhanhTran1307"
# REPO_NAME = "sentiment-analysis-api"

# import subprocess

# # Nhúng token thẳng vào URL

# subprocess.run(["git", "remote", "remove", "origin"])
# subprocess.run(["git", "remote", "add", "origin", remote_url])
# subprocess.run(["git", "add", "main.py", "test_api.py", "requirements.txt", "README.md"])
# subprocess.run(["git", "commit", "--allow-empty", "-m", "add project files"])
# subprocess.run(["git", "push", "-u", "origin", "main"])
# print("Done!")

with open("main.py", "r") as f:
    print(f.read())

import requests

BASE_URL = "http://localhost:8000"  # hoặc URL ngrok của bạn

# Test 1: GET /
r = requests.get(f"{BASE_URL}/")
print("=== GET / ===")
print(r.json())

# Test 2: GET /health
r = requests.get(f"{BASE_URL}/health")
print("\n=== GET /health ===")
print(r.json())

# Test 3: Câu tích cực
r = requests.post(f"{BASE_URL}/predict", json={"text": "I love this product, it is amazing!"})
print("\n=== POST /predict (tích cực) ===")
print(r.json())

# Test 4: Câu tiêu cực
r = requests.post(f"{BASE_URL}/predict", json={"text": "This is the worst experience I have ever had."})
print("\n=== POST /predict (tiêu cực) ===")
print(r.json())

# Test 5: \\
r = requests.post(f"{BASE_URL}/predict", json={"text": ""})
print("\n=== POST /predict (text rỗng) ===")
print(r.json())

